/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import codigos.Classificador;
import codigos.Log;
import codigos.Padrao;
import javax.swing.JOptionPane;

/**
 *
 * @author caio_
 */
public class tela_comparacao extends javax.swing.JFrame {

    double IDADE;
    int G1;
    int G2;
    double GRAU;
    int ET1, ET2, ET3, ET4, ET5, ET6, ET7;

    String result;
    
    public tela_comparacao() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextLog = new javax.swing.JTextArea();
        titulo = new javax.swing.JLabel();
        jComboSexo = new javax.swing.JComboBox<>();
        Idade = new javax.swing.JLabel();
        txtIdade = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboEducacao = new javax.swing.JComboBox<>();
        jComboEtnia = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtAlcool = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAnfetaminas = new javax.swing.JTextField();
        txtNitrito = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtBenzodiazepina = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCafeina = new javax.swing.JTextField();
        txtMaconha = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtChocolate = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtCocaina = new javax.swing.JTextField();
        txtCrack = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtEcstasy = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtHeroina = new javax.swing.JTextField();
        txtKetamina = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtDrogas = new javax.swing.JTextField();
        txtLsd = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtMetadona = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtCogumelos = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtNicotina = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtVsa = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        Sexo1 = new javax.swing.JLabel();
        Sexo2 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtAlcool1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtAnfetaminas1 = new javax.swing.JTextField();
        txtNitrito1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtBenzodiazepina1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtCafeina1 = new javax.swing.JTextField();
        txtMaconha1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtChocolate1 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtCocaina1 = new javax.swing.JTextField();
        txtCrack1 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtEcstasy1 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txtHeroina1 = new javax.swing.JTextField();
        txtKetamina1 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txtDrogas1 = new javax.swing.JTextField();
        txtLsd1 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txtMetadona1 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        txtCogumelos1 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        txtNicotina1 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        txtVsa1 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        Sexo3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Classificador de Risco");
        setResizable(false);
        setSize(new java.awt.Dimension(1230, 580));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextLog.setEditable(false);
        jTextLog.setColumns(20);
        jTextLog.setRows(5);
        jScrollPane1.setViewportView(jTextLog);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, 470, 460));

        titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titulo.setText("K- DRUGS CLASSIFIER");
        jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        jComboSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));
        jComboSexo.setEnabled(false);
        jComboSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboSexoActionPerformed(evt);
            }
        });
        jPanel1.add(jComboSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 98, -1));

        Idade.setText("Idade :");
        jPanel1.add(Idade, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        txtIdade.setEnabled(false);
        txtIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdadeActionPerformed(evt);
            }
        });
        jPanel1.add(txtIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 35, -1));

        jLabel1.setText("Etnia :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        jLabel2.setText("Educação :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, 220, -1));

        jComboEducacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desistiu da escola antes dos 16 Anos", "Desistiu da escola aos 16 anos", "Desistiu da escola aos 17 anos", "Desistiu da escola aos 18 anos","Alguma facul/uni sem certificado ou grau","Certificado / diploma profissional","Diploma Universitário","Mestrado","Doutorado" }));
        jComboEducacao.setEnabled(false);
        jPanel1.add(jComboEducacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, 560, -1));

        jComboEtnia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Asiático", "Negro","Branco", "Misto Negro/Asiatico", "Misto Branco/Asiatico","Misto Branco/Negro","Outro" }));
        jComboEtnia.setEnabled(false);
        jPanel1.add(jComboEtnia, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 219, -1));

        jLabel3.setText("Resultados para a comparação com uma base menor:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 80, -1, -1));

        jLabel4.setText("Alcool");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        txtAlcool.setEditable(false);
        txtAlcool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlcoolActionPerformed(evt);
            }
        });
        jPanel1.add(txtAlcool, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 100, -1));

        jLabel5.setText("Anfetaminas");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        txtAnfetaminas.setEditable(false);
        txtAnfetaminas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnfetaminasActionPerformed(evt);
            }
        });
        jPanel1.add(txtAnfetaminas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 100, -1));

        txtNitrito.setEditable(false);
        txtNitrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNitritoActionPerformed(evt);
            }
        });
        jPanel1.add(txtNitrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 100, -1));

        jLabel6.setText("Nitrito");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        txtBenzodiazepina.setEditable(false);
        txtBenzodiazepina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBenzodiazepinaActionPerformed(evt);
            }
        });
        jPanel1.add(txtBenzodiazepina, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 100, -1));

        jLabel7.setText("Benzodiazepina");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, -1));

        jLabel8.setText("Cafeína");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, -1, -1));

        txtCafeina.setEditable(false);
        txtCafeina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCafeinaActionPerformed(evt);
            }
        });
        jPanel1.add(txtCafeina, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 100, -1));

        txtMaconha.setEditable(false);
        txtMaconha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaconhaActionPerformed(evt);
            }
        });
        jPanel1.add(txtMaconha, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 100, -1));

        jLabel9.setText("Maconha");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, -1, -1));

        txtChocolate.setEditable(false);
        txtChocolate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChocolateActionPerformed(evt);
            }
        });
        jPanel1.add(txtChocolate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 100, -1));

        jLabel10.setText("Chocolate");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel11.setText("Cocaina");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        txtCocaina.setEditable(false);
        txtCocaina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCocainaActionPerformed(evt);
            }
        });
        jPanel1.add(txtCocaina, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 100, -1));

        txtCrack.setEditable(false);
        txtCrack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCrackActionPerformed(evt);
            }
        });
        jPanel1.add(txtCrack, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 100, -1));

        jLabel12.setText("Crack");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));

        txtEcstasy.setEditable(false);
        txtEcstasy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEcstasyActionPerformed(evt);
            }
        });
        jPanel1.add(txtEcstasy, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 100, -1));

        jLabel13.setText("Ecstasy");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel14.setText("Heroina");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));

        txtHeroina.setEditable(false);
        txtHeroina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHeroinaActionPerformed(evt);
            }
        });
        jPanel1.add(txtHeroina, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 100, -1));

        txtKetamina.setEditable(false);
        txtKetamina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKetaminaActionPerformed(evt);
            }
        });
        jPanel1.add(txtKetamina, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 100, -1));

        jLabel15.setText("ketamina");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));

        jLabel16.setText("Drogas Legais");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 90, -1));

        txtDrogas.setEditable(false);
        txtDrogas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDrogasActionPerformed(evt);
            }
        });
        jPanel1.add(txtDrogas, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 100, -1));

        txtLsd.setEditable(false);
        txtLsd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLsdActionPerformed(evt);
            }
        });
        jPanel1.add(txtLsd, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 100, -1));

        jLabel17.setText("LSD");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, -1, -1));

        txtMetadona.setEditable(false);
        txtMetadona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMetadonaActionPerformed(evt);
            }
        });
        jPanel1.add(txtMetadona, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 100, -1));

        jLabel18.setText("Metadona");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));

        txtCogumelos.setEditable(false);
        txtCogumelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCogumelosActionPerformed(evt);
            }
        });
        jPanel1.add(txtCogumelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 100, -1));

        jLabel19.setText("Cogumelos Magicos");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, -1));

        txtNicotina.setEditable(false);
        txtNicotina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNicotinaActionPerformed(evt);
            }
        });
        jPanel1.add(txtNicotina, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 100, -1));

        jLabel20.setText("Nicotina");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, -1, -1));

        jLabel21.setText("VSA");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, -1, -1));

        txtVsa.setEditable(false);
        txtVsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVsaActionPerformed(evt);
            }
        });
        jPanel1.add(txtVsa, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 100, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 690, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 690, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 690, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 690, 10));

        Sexo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Sexo1.setText("Resultado com base completa:");
        jPanel1.add(Sexo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        Sexo2.setText("Sexo :");
        jPanel1.add(Sexo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel22.setText("Alcool");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        txtAlcool1.setEditable(false);
        txtAlcool1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlcool1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtAlcool1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 100, -1));

        jLabel23.setText("Anfetaminas");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, -1));

        txtAnfetaminas1.setEditable(false);
        txtAnfetaminas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnfetaminas1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtAnfetaminas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 100, -1));

        txtNitrito1.setEditable(false);
        txtNitrito1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNitrito1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtNitrito1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 100, -1));

        jLabel24.setText("Nitrito");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, -1, -1));

        txtBenzodiazepina1.setEditable(false);
        txtBenzodiazepina1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBenzodiazepina1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtBenzodiazepina1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 100, -1));

        jLabel25.setText("Benzodiazepina");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, -1, -1));

        jLabel26.setText("Cafeína");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, -1, -1));

        txtCafeina1.setEditable(false);
        txtCafeina1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCafeina1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtCafeina1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 100, -1));

        txtMaconha1.setEditable(false);
        txtMaconha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaconha1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtMaconha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 100, -1));

        jLabel27.setText("Maconha");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 330, -1, -1));

        txtChocolate1.setEditable(false);
        txtChocolate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChocolate1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtChocolate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 100, -1));

        jLabel28.setText("Chocolate");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jLabel29.setText("Cocaina");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, -1, -1));

        txtCocaina1.setEditable(false);
        txtCocaina1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCocaina1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtCocaina1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 100, -1));

        txtCrack1.setEditable(false);
        txtCrack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCrack1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtCrack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 100, -1));

        jLabel30.setText("Crack");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, -1, -1));

        txtEcstasy1.setEditable(false);
        txtEcstasy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEcstasy1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtEcstasy1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 100, -1));

        jLabel31.setText("Ecstasy");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));

        jLabel32.setText("Heroina");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, -1, -1));

        txtHeroina1.setEditable(false);
        txtHeroina1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHeroina1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtHeroina1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 100, -1));

        txtKetamina1.setEditable(false);
        txtKetamina1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKetamina1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtKetamina1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 100, -1));

        jLabel33.setText("ketamina");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, -1, -1));

        jLabel34.setText("Drogas Legais");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 90, -1));

        txtDrogas1.setEditable(false);
        txtDrogas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDrogas1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtDrogas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, 100, -1));

        txtLsd1.setEditable(false);
        txtLsd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLsd1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtLsd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 100, -1));

        jLabel35.setText("LSD");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, -1, -1));

        txtMetadona1.setEditable(false);
        txtMetadona1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMetadona1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtMetadona1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 470, 100, -1));

        jLabel36.setText("Metadona");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, -1, -1));

        txtCogumelos1.setEditable(false);
        txtCogumelos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCogumelos1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtCogumelos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, 100, -1));

        jLabel37.setText("Cogumelos Magicos");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, -1, -1));

        txtNicotina1.setEditable(false);
        txtNicotina1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNicotina1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtNicotina1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, 100, -1));

        jLabel38.setText("Nicotina");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, -1, -1));

        jLabel39.setText("VSA");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 450, -1, -1));

        txtVsa1.setEditable(false);
        txtVsa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVsa1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtVsa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 100, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 690, 10));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 690, 10));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 690, 10));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 690, 10));

        Sexo3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Sexo3.setText("Resultado com base parcial:");
        jPanel1.add(Sexo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1230, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtVsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVsaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVsaActionPerformed

    private void txtNicotinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNicotinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNicotinaActionPerformed

    private void txtCogumelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCogumelosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCogumelosActionPerformed

    private void txtMetadonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMetadonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMetadonaActionPerformed

    private void txtLsdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLsdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLsdActionPerformed

    private void txtDrogasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDrogasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDrogasActionPerformed

    private void txtKetaminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKetaminaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKetaminaActionPerformed

    private void txtHeroinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHeroinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHeroinaActionPerformed

    private void txtEcstasyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEcstasyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEcstasyActionPerformed

    private void txtCrackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCrackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCrackActionPerformed

    private void txtCocainaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCocainaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCocainaActionPerformed

    private void txtChocolateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChocolateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChocolateActionPerformed

    private void txtMaconhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaconhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaconhaActionPerformed

    private void txtCafeinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCafeinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCafeinaActionPerformed

    private void txtBenzodiazepinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBenzodiazepinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBenzodiazepinaActionPerformed

    private void txtNitritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNitritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNitritoActionPerformed

    private void txtAnfetaminasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnfetaminasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnfetaminasActionPerformed

    private void txtAlcoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlcoolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlcoolActionPerformed

    private void txtIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdadeActionPerformed

    private void jComboSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboSexoActionPerformed

    private void txtAlcool1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlcool1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlcool1ActionPerformed

    private void txtAnfetaminas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnfetaminas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnfetaminas1ActionPerformed

    private void txtNitrito1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNitrito1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNitrito1ActionPerformed

    private void txtBenzodiazepina1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBenzodiazepina1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBenzodiazepina1ActionPerformed

    private void txtCafeina1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCafeina1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCafeina1ActionPerformed

    private void txtMaconha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaconha1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaconha1ActionPerformed

    private void txtChocolate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChocolate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChocolate1ActionPerformed

    private void txtCocaina1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCocaina1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCocaina1ActionPerformed

    private void txtCrack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCrack1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCrack1ActionPerformed

    private void txtEcstasy1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEcstasy1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEcstasy1ActionPerformed

    private void txtHeroina1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHeroina1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHeroina1ActionPerformed

    private void txtKetamina1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKetamina1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKetamina1ActionPerformed

    private void txtDrogas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDrogas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDrogas1ActionPerformed

    private void txtLsd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLsd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLsd1ActionPerformed

    private void txtMetadona1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMetadona1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMetadona1ActionPerformed

    private void txtCogumelos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCogumelos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCogumelos1ActionPerformed

    private void txtNicotina1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNicotina1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNicotina1ActionPerformed

    private void txtVsa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVsa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVsa1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_comparacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_comparacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_comparacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_comparacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_comparacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Idade;
    private javax.swing.JLabel Sexo1;
    private javax.swing.JLabel Sexo2;
    private javax.swing.JLabel Sexo3;
    private javax.swing.JComboBox<String> jComboEducacao;
    private javax.swing.JComboBox<String> jComboEtnia;
    private javax.swing.JComboBox<String> jComboSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextArea jTextLog;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtAlcool;
    private javax.swing.JTextField txtAlcool1;
    private javax.swing.JTextField txtAnfetaminas;
    private javax.swing.JTextField txtAnfetaminas1;
    private javax.swing.JTextField txtBenzodiazepina;
    private javax.swing.JTextField txtBenzodiazepina1;
    private javax.swing.JTextField txtCafeina;
    private javax.swing.JTextField txtCafeina1;
    private javax.swing.JTextField txtChocolate;
    private javax.swing.JTextField txtChocolate1;
    private javax.swing.JTextField txtCocaina;
    private javax.swing.JTextField txtCocaina1;
    private javax.swing.JTextField txtCogumelos;
    private javax.swing.JTextField txtCogumelos1;
    private javax.swing.JTextField txtCrack;
    private javax.swing.JTextField txtCrack1;
    private javax.swing.JTextField txtDrogas;
    private javax.swing.JTextField txtDrogas1;
    private javax.swing.JTextField txtEcstasy;
    private javax.swing.JTextField txtEcstasy1;
    private javax.swing.JTextField txtHeroina;
    private javax.swing.JTextField txtHeroina1;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtKetamina;
    private javax.swing.JTextField txtKetamina1;
    private javax.swing.JTextField txtLsd;
    private javax.swing.JTextField txtLsd1;
    private javax.swing.JTextField txtMaconha;
    private javax.swing.JTextField txtMaconha1;
    private javax.swing.JTextField txtMetadona;
    private javax.swing.JTextField txtMetadona1;
    private javax.swing.JTextField txtNicotina;
    private javax.swing.JTextField txtNicotina1;
    private javax.swing.JTextField txtNitrito;
    private javax.swing.JTextField txtNitrito1;
    private javax.swing.JTextField txtVsa;
    private javax.swing.JTextField txtVsa1;
    // End of variables declaration//GEN-END:variables

    public void converteSexo(String sexo) {
        if (sexo.equals("Masculino")) {
            G1 = 0;
            G2 = 1;
        } else {
            G1 = 1;
            G2 = 0;
        }
    }

    public void converteIdade(int idade) {

        if (idade >= 18 && idade <= 24) {
            IDADE = 0;
        } else if (idade > 24 && idade <= 34) {
            IDADE = 0.246;
        } else if (idade > 34 && idade <= 44) {
            IDADE = 0.409;
        } else if (idade > 44 && idade <= 54) {
            IDADE = 0.577;
        } else if (idade > 54 && idade <= 64) {
            IDADE = 0.783;
        } else if (idade > 64) {
            IDADE = 1;
        } else {
            IDADE = -1;
        }

    }

    public void converteEducacao(String educa) {
        switch (educa) {
            case "Desistiu da escola antes dos 16 Anos":
                GRAU = 0;
                break;
            case "Desistiu da escola aos 16 anos":
                GRAU = 0.158;
                break;
            case "Desistiu da escola aos 17 anos":
                GRAU = 0.226;
                break;
            case "Desistiu da escola aos 18 anos":
                GRAU = 0.273;
                break;
            case "Alguma facul/uni sem certificado ou grau":
                GRAU = 0.413;
                break;
            case "Certificado / diploma profissional":
                GRAU = 0.538;
                break;
            case "Diploma Universitário":
                GRAU = 0.654;
                break;
            case "Mestrado":
                GRAU = 0.814;
                break;
            case "Doutorado":
                GRAU = 1;
                break;
        }
    }

    public void converteEtnia(String etnia) {
        switch (etnia) {
            case "Asiático":
                ET1 = 0;
                ET2 = 0;
                ET3 = 0;
                ET4 = 0;
                ET5 = 0;
                ET6 = 0;
                ET7 = 1;
                break;
            case "Negro":
                ET1 = 0;
                ET2 = 0;
                ET3 = 0;
                ET4 = 0;
                ET5 = 0;
                ET6 = 1;
                ET7 = 0;
                break;
            case "Branco":
                ET1 = 1;
                ET2 = 0;
                ET3 = 0;
                ET4 = 0;
                ET5 = 0;
                ET6 = 0;
                ET7 = 0;
                break;
            case "Misto Negro/Asiatico":
                ET1 = 0;
                ET2 = 0;
                ET3 = 0;
                ET4 = 0;
                ET5 = 1;
                ET6 = 0;
                ET7 = 0;
                break;
            case "Misto Branco/Asiatico":
                ET1 = 0;
                ET2 = 0;
                ET3 = 0;
                ET4 = 1;
                ET5 = 0;
                ET6 = 0;
                ET7 = 0;
                break;
            case "Misto Branco/Negro":
                ET1 = 0;
                ET2 = 0;
                ET3 = 1;
                ET4 = 0;
                ET5 = 0;
                ET6 = 0;
                ET7 = 0;
                break;
            case "Outro":
                ET1 = 0;
                ET2 = 1;
                ET3 = 0;
                ET4 = 0;
                ET5 = 0;
                ET6 = 0;
                ET7 = 0;
                break;
        }

    }

    public String classifica(String r) {
        switch (r) {
            case "CL0":
                return "Baixo";
            case "CL1":
                return "Baixo";
            case "CL2":
                return "Medio";
            case "CL3":
                return "Medio";
            case "CL4":
                return "Alto";
            case "CL5":
                return "Alto";
            case "CL6":
                return "Alto";
            default:
                return "Error";
        }
    }
}
