/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import codigos.Classificador;
import codigos.ClassificadorParcial;
import codigos.Log;
import codigos.Padrao;
import javax.swing.JOptionPane;

/**
 *
 * @author caio_
 */
public class tela_principal extends javax.swing.JFrame {

    double IDADE;
    int G1;
    int G2;
    double GRAU;
    int ET1, ET2, ET3, ET4, ET5, ET6, ET7;
    
    String result;

    public tela_principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextLog = new javax.swing.JTextArea();
        titulo = new javax.swing.JLabel();
        jComboSexo = new javax.swing.JComboBox<>();
        Sexo = new javax.swing.JLabel();
        Idade = new javax.swing.JLabel();
        txtIdade = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboEducacao = new javax.swing.JComboBox<>();
        jComboEtnia = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtAlcool = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAnfetaminas = new javax.swing.JTextField();
        txtNitrito = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtBenzodiazepina = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCafeina = new javax.swing.JTextField();
        txtMaconha = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtChocolate = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtCocaina = new javax.swing.JTextField();
        txtCrack = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtEcstasy = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtHeroina = new javax.swing.JTextField();
        txtKetamina = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtDrogas = new javax.swing.JTextField();
        txtLsd = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtMetadona = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtCogumelos = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtNicotina = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtVsa = new javax.swing.JTextField();
        btnClassificar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        btnLimpar = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        btnComparar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Classificador de Risco");
        setResizable(false);
        setSize(new java.awt.Dimension(1230, 580));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextLog.setEditable(false);
        jTextLog.setColumns(20);
        jTextLog.setRows(5);
        jScrollPane1.setViewportView(jTextLog);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, 470, 460));

        titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titulo.setText("Classificador de Risco ( Drogas )");
        jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 11, -1, -1));

        jComboSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));
        jComboSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboSexoActionPerformed(evt);
            }
        });
        jPanel1.add(jComboSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 78, 98, -1));

        Sexo.setText("Sexo :");
        jPanel1.add(Sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 81, -1, -1));

        Idade.setText("Idade :");
        jPanel1.add(Idade, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 81, -1, -1));

        txtIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdadeActionPerformed(evt);
            }
        });
        jPanel1.add(txtIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 78, 35, -1));

        jLabel1.setText("Etnia :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 81, -1, -1));

        jLabel2.setText("Educação :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jComboEducacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desistiu da escola antes dos 16 Anos", "Desistiu da escola aos 16 anos", "Desistiu da escola aos 17 anos", "Desistiu da escola aos 18 anos","Alguma facul/uni sem certificado ou grau","Certificado / diploma profissional","Diploma Universitário","Mestrado","Doutorado" }));
        jPanel1.add(jComboEducacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 450, -1));

        jComboEtnia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Asiático", "Negro","Branco", "Misto Negro/Asiatico", "Misto Branco/Asiatico","Misto Branco/Negro","Outro" }));
        jPanel1.add(jComboEtnia, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 78, 219, -1));

        jLabel3.setText("Log");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 80, -1, -1));

        jLabel4.setText("Alcool");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        txtAlcool.setEditable(false);
        txtAlcool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlcoolActionPerformed(evt);
            }
        });
        jPanel1.add(txtAlcool, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 100, -1));

        jLabel5.setText("Anfetaminas");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        txtAnfetaminas.setEditable(false);
        txtAnfetaminas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnfetaminasActionPerformed(evt);
            }
        });
        jPanel1.add(txtAnfetaminas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 100, -1));

        txtNitrito.setEditable(false);
        txtNitrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNitritoActionPerformed(evt);
            }
        });
        jPanel1.add(txtNitrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 100, -1));

        jLabel6.setText("Nitrito");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, -1));

        txtBenzodiazepina.setEditable(false);
        txtBenzodiazepina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBenzodiazepinaActionPerformed(evt);
            }
        });
        jPanel1.add(txtBenzodiazepina, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 100, -1));

        jLabel7.setText("Benzodiazepina");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, -1, -1));

        jLabel8.setText("Cafeína");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, -1, -1));

        txtCafeina.setEditable(false);
        txtCafeina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCafeinaActionPerformed(evt);
            }
        });
        jPanel1.add(txtCafeina, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 100, -1));

        txtMaconha.setEditable(false);
        txtMaconha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaconhaActionPerformed(evt);
            }
        });
        jPanel1.add(txtMaconha, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 100, -1));

        jLabel9.setText("Maconha");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, -1, -1));

        txtChocolate.setEditable(false);
        txtChocolate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChocolateActionPerformed(evt);
            }
        });
        jPanel1.add(txtChocolate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 100, -1));

        jLabel10.setText("Chocolate");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jLabel11.setText("Cocaina");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, -1));

        txtCocaina.setEditable(false);
        txtCocaina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCocainaActionPerformed(evt);
            }
        });
        jPanel1.add(txtCocaina, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 100, -1));

        txtCrack.setEditable(false);
        txtCrack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCrackActionPerformed(evt);
            }
        });
        jPanel1.add(txtCrack, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 100, -1));

        jLabel12.setText("Crack");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, -1, -1));

        txtEcstasy.setEditable(false);
        txtEcstasy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEcstasyActionPerformed(evt);
            }
        });
        jPanel1.add(txtEcstasy, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 100, -1));

        jLabel13.setText("Ecstasy");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        jLabel14.setText("Heroina");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, -1, -1));

        txtHeroina.setEditable(false);
        txtHeroina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHeroinaActionPerformed(evt);
            }
        });
        jPanel1.add(txtHeroina, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 100, -1));

        txtKetamina.setEditable(false);
        txtKetamina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKetaminaActionPerformed(evt);
            }
        });
        jPanel1.add(txtKetamina, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 100, -1));

        jLabel15.setText("ketamina");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, -1, -1));

        jLabel16.setText("Drogas Legais");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 90, -1));

        txtDrogas.setEditable(false);
        txtDrogas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDrogasActionPerformed(evt);
            }
        });
        jPanel1.add(txtDrogas, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 100, -1));

        txtLsd.setEditable(false);
        txtLsd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLsdActionPerformed(evt);
            }
        });
        jPanel1.add(txtLsd, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 100, -1));

        jLabel17.setText("LSD");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, -1, -1));

        txtMetadona.setEditable(false);
        txtMetadona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMetadonaActionPerformed(evt);
            }
        });
        jPanel1.add(txtMetadona, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, 100, -1));

        jLabel18.setText("Metadona");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, -1, -1));

        txtCogumelos.setEditable(false);
        txtCogumelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCogumelosActionPerformed(evt);
            }
        });
        jPanel1.add(txtCogumelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 100, -1));

        jLabel19.setText("Cogumelos Magicos");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, -1, -1));

        txtNicotina.setEditable(false);
        txtNicotina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNicotinaActionPerformed(evt);
            }
        });
        jPanel1.add(txtNicotina, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, 100, -1));

        jLabel20.setText("Nicotina");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, -1, -1));

        jLabel21.setText("VSA");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 400, -1, -1));

        txtVsa.setEditable(false);
        txtVsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVsaActionPerformed(evt);
            }
        });
        jPanel1.add(txtVsa, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 100, -1));

        btnClassificar.setText("Classificar");
        btnClassificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClassificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnClassificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 150, 33));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 690, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 207, 690, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 690, 10));

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 136, 33));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 690, 10));

        btnComparar.setText("Comparar(base parcial)");
        btnComparar.setEnabled(false);
        btnComparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompararActionPerformed(evt);
            }
        });
        jPanel1.add(btnComparar, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 160, 210, 33));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1230, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtVsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVsaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVsaActionPerformed

    private void txtNicotinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNicotinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNicotinaActionPerformed

    private void txtCogumelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCogumelosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCogumelosActionPerformed

    private void txtMetadonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMetadonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMetadonaActionPerformed

    private void txtLsdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLsdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLsdActionPerformed

    private void txtDrogasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDrogasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDrogasActionPerformed

    private void txtKetaminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKetaminaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKetaminaActionPerformed

    private void txtHeroinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHeroinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHeroinaActionPerformed

    private void txtEcstasyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEcstasyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEcstasyActionPerformed

    private void txtCrackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCrackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCrackActionPerformed

    private void txtCocainaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCocainaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCocainaActionPerformed

    private void txtChocolateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChocolateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChocolateActionPerformed

    private void txtMaconhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaconhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaconhaActionPerformed

    private void txtCafeinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCafeinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCafeinaActionPerformed

    private void txtBenzodiazepinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBenzodiazepinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBenzodiazepinaActionPerformed

    private void txtNitritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNitritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNitritoActionPerformed

    private void txtAnfetaminasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnfetaminasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnfetaminasActionPerformed

    private void txtAlcoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlcoolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlcoolActionPerformed

    private void txtIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdadeActionPerformed

    private void jComboSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboSexoActionPerformed

    private void btnClassificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClassificarActionPerformed

        converteSexo((String) jComboSexo.getSelectedItem());
        converteIdade(Integer.parseInt(txtIdade.getText()));
        converteEducacao((String) jComboEducacao.getSelectedItem());
        converteEtnia((String) jComboEtnia.getSelectedItem());
        if (IDADE == -1) {
            JOptionPane.showMessageDialog(null,"Idade Inválida !");
        } else {
            Padrao p = new Padrao(IDADE, G1, G2, GRAU, ET1, ET2, ET3, ET4, ET5, ET6, ET7, null, 0);
            Classificador k = new Classificador();
            result = k.classifica(p);
            String[] r = result.split(":");

            txtAlcool.setText(classifica(r[0]));
            txtAnfetaminas.setText(classifica(r[1]));
            txtNitrito.setText(classifica(r[2]));
            txtBenzodiazepina.setText(classifica(r[3]));
            txtCafeina.setText(classifica(r[4]));
            txtMaconha.setText(classifica(r[5]));
            txtChocolate.setText(classifica(r[6]));
            txtCocaina.setText(classifica(r[7]));
            txtCrack.setText(classifica(r[9]));
            txtEcstasy.setText(classifica(r[10]));
            txtHeroina.setText(classifica(r[11]));
            txtKetamina.setText(classifica(r[12]));
            txtDrogas.setText(classifica(r[13]));
            txtLsd.setText(classifica(r[14]));
            txtMetadona.setText(classifica(r[15]));
            txtCogumelos.setText(classifica(r[16]));
            txtNicotina.setText(classifica(r[18]));
            txtVsa.setText(classifica(r[19]));

            jTextLog.setText(Log.resumo());          
            
            btnComparar.setEnabled(true);
        }


    }//GEN-LAST:event_btnClassificarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        Log.LOG.clear();
        txtAlcool.setText("");
            txtAnfetaminas.setText("");
            txtNitrito.setText("");
            txtBenzodiazepina.setText("");
            txtCafeina.setText("");
            txtMaconha.setText("");
            txtChocolate.setText("");
            txtCocaina.setText("");
            txtCrack.setText("");
            txtEcstasy.setText("");
            txtHeroina.setText("");
            txtKetamina.setText("");
            txtDrogas.setText("");
            txtLsd.setText("");
            txtMetadona.setText("");
            txtCogumelos.setText("");
            txtNicotina.setText("");
            txtVsa.setText("");
            jTextLog.setText("");
            
        
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnCompararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompararActionPerformed
        tela_comparacao tc = new tela_comparacao();
        tc.preencherClassificarGeral(result,jComboSexo.getSelectedIndex(),txtIdade.getText(),jComboEducacao.getSelectedIndex(),jComboEtnia.getSelectedIndex());
        tc.classificarParcial(new Padrao(IDADE, G1, G2, GRAU, ET1, ET2, ET3, ET4, ET5, ET6, ET7, null, 0));
        tc.show();
    }//GEN-LAST:event_btnCompararActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Idade;
    private javax.swing.JLabel Sexo;
    private javax.swing.JButton btnClassificar;
    private javax.swing.JButton btnComparar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JComboBox<String> jComboEducacao;
    private javax.swing.JComboBox<String> jComboEtnia;
    private javax.swing.JComboBox<String> jComboSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextArea jTextLog;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtAlcool;
    private javax.swing.JTextField txtAnfetaminas;
    private javax.swing.JTextField txtBenzodiazepina;
    private javax.swing.JTextField txtCafeina;
    private javax.swing.JTextField txtChocolate;
    private javax.swing.JTextField txtCocaina;
    private javax.swing.JTextField txtCogumelos;
    private javax.swing.JTextField txtCrack;
    private javax.swing.JTextField txtDrogas;
    private javax.swing.JTextField txtEcstasy;
    private javax.swing.JTextField txtHeroina;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtKetamina;
    private javax.swing.JTextField txtLsd;
    private javax.swing.JTextField txtMaconha;
    private javax.swing.JTextField txtMetadona;
    private javax.swing.JTextField txtNicotina;
    private javax.swing.JTextField txtNitrito;
    private javax.swing.JTextField txtVsa;
    // End of variables declaration//GEN-END:variables

    public void converteSexo(String sexo) {
        if (sexo.equals("Masculino")) {
            G1 = 0;
            G2 = 1;
        } else {
            G1 = 1;
            G2 = 0;
        }
    }

    public void converteIdade(int idade) {

        if (idade >= 18 && idade <= 24) {
            IDADE = 0;
        } else if (idade > 24 && idade <= 34) {
            IDADE = 0.246;
        } else if (idade > 34 && idade <= 44) {
            IDADE = 0.409;
        } else if (idade > 44 && idade <= 54) {
            IDADE = 0.577;
        } else if (idade > 54 && idade <= 64) {
            IDADE = 0.783;
        } else if (idade > 64) {
            IDADE = 1;
        } else {
            IDADE = -1;
        }

    }

    public void converteEducacao(String educa) {
        switch (educa) {
            case "Desistiu da escola antes dos 16 Anos":
                GRAU = 0;
                break;
            case "Desistiu da escola aos 16 anos":
                GRAU = 0.158;
                break;
            case "Desistiu da escola aos 17 anos":
                GRAU = 0.226;
                break;
            case "Desistiu da escola aos 18 anos":
                GRAU = 0.273;
                break;
            case "Alguma facul/uni sem certificado ou grau":
                GRAU = 0.413;
                break;
            case "Certificado / diploma profissional":
                GRAU = 0.538;
                break;
            case "Diploma Universitário":
                GRAU = 0.654;
                break;
            case "Mestrado":
                GRAU = 0.814;
                break;
            case "Doutorado":
                GRAU = 1;
                break;
        }
    }

    public void converteEtnia(String etnia) {
        switch (etnia) {
            case "Asiático":
                ET1 = 0;
                ET2 = 0;
                ET3 = 0;
                ET4 = 0;
                ET5 = 0;
                ET6 = 0;
                ET7 = 1;
                break;
            case "Negro":
                ET1 = 0;
                ET2 = 0;
                ET3 = 0;
                ET4 = 0;
                ET5 = 0;
                ET6 = 1;
                ET7 = 0;
                break;
            case "Branco":
                ET1 = 1;
                ET2 = 0;
                ET3 = 0;
                ET4 = 0;
                ET5 = 0;
                ET6 = 0;
                ET7 = 0;
                break;
            case "Misto Negro/Asiatico":
                ET1 = 0;
                ET2 = 0;
                ET3 = 0;
                ET4 = 0;
                ET5 = 1;
                ET6 = 0;
                ET7 = 0;
                break;
            case "Misto Branco/Asiatico":
                ET1 = 0;
                ET2 = 0;
                ET3 = 0;
                ET4 = 1;
                ET5 = 0;
                ET6 = 0;
                ET7 = 0;
                break;
            case "Misto Branco/Negro":
                ET1 = 0;
                ET2 = 0;
                ET3 = 1;
                ET4 = 0;
                ET5 = 0;
                ET6 = 0;
                ET7 = 0;
                break;
            case "Outro":
                ET1 = 0;
                ET2 = 1;
                ET3 = 0;
                ET4 = 0;
                ET5 = 0;
                ET6 = 0;
                ET7 = 0;
                break;
        }

    }

    public String classifica(String r) {
        switch (r) {
            case "CL0":
                return "Baixo";
            case "CL1":
                return "Baixo";
            case "CL2":
                return "Medio";
            case "CL3":
                return "Medio";
            case "CL4":
                return "Alto";
            case "CL5":
                return "Alto";
            case "CL6":
                return "Alto";
            default:
                return "Error";
        }
    }
}
