/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import codigos.Classificador;
import codigos.Log;
import codigos.LogClassParcial;
import codigos.Padrao;
import javax.swing.JOptionPane;

/**
 *
 * @author caio_
 */
public class tela_principal extends javax.swing.JFrame {

    double IDADE;
    int G1;
    int G2;
    double GRAU;
    int ET1, ET2, ET3, ET4, ET5, ET6, ET7;
    Classificador k;
    String result;

    public tela_principal() {
        initComponents();
        k = new Classificador();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextLog = new javax.swing.JTextArea();
        titulo = new javax.swing.JLabel();
        jComboSexo = new javax.swing.JComboBox<>();
        Sexo = new javax.swing.JLabel();
        Idade = new javax.swing.JLabel();
        txtIdade = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboEducacao = new javax.swing.JComboBox<>();
        jComboEtnia = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtAlcool = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAnfetaminas = new javax.swing.JTextField();
        txtNitrito = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtBenzodiazepina = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCafeina = new javax.swing.JTextField();
        txtMaconha = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtChocolate = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtCocaina = new javax.swing.JTextField();
        txtCrack = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtEcstasy = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtHeroina = new javax.swing.JTextField();
        txtKetamina = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtDrogas = new javax.swing.JTextField();
        txtLsd = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtMetadona = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtCogumelos = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtNicotina = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtVsa = new javax.swing.JTextField();
        btnClassificar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        btnLimpar = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        btnComparar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Classificador de Risco");
        setResizable(false);
        setSize(new java.awt.Dimension(1230, 580));

        jTextLog.setEditable(false);
        jTextLog.setColumns(20);
        jTextLog.setRows(5);
        jScrollPane1.setViewportView(jTextLog);

        titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titulo.setText("K- DRUGS CLASSIFIER");

        jComboSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));
        jComboSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboSexoActionPerformed(evt);
            }
        });

        Sexo.setText("Sexo :");

        Idade.setText("Idade :");

        txtIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdadeActionPerformed(evt);
            }
        });

        jLabel1.setText("Etnia :");

        jLabel2.setText("Educação :");

        jComboEducacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desistiu da escola antes dos 16 Anos", "Desistiu da escola aos 16 anos", "Desistiu da escola aos 17 anos", "Desistiu da escola aos 18 anos","Alguma facul/uni sem certificado ou grau","Certificado / diploma profissional","Diploma Universitário","Mestrado","Doutorado" }));

        jComboEtnia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Asiático", "Negro","Branco", "Misto Negro/Asiatico", "Misto Branco/Asiatico","Misto Branco/Negro","Outro" }));

        jLabel3.setText("Log");

        jLabel4.setText("Alcool");

        txtAlcool.setEditable(false);
        txtAlcool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlcoolActionPerformed(evt);
            }
        });

        jLabel5.setText("Anfetaminas");

        txtAnfetaminas.setEditable(false);
        txtAnfetaminas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnfetaminasActionPerformed(evt);
            }
        });

        txtNitrito.setEditable(false);
        txtNitrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNitritoActionPerformed(evt);
            }
        });

        jLabel6.setText("Nitrito");

        txtBenzodiazepina.setEditable(false);
        txtBenzodiazepina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBenzodiazepinaActionPerformed(evt);
            }
        });

        jLabel7.setText("Benzodiazepina");

        jLabel8.setText("Cafeína");

        txtCafeina.setEditable(false);
        txtCafeina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCafeinaActionPerformed(evt);
            }
        });

        txtMaconha.setEditable(false);
        txtMaconha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaconhaActionPerformed(evt);
            }
        });

        jLabel9.setText("Maconha");

        txtChocolate.setEditable(false);
        txtChocolate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChocolateActionPerformed(evt);
            }
        });

        jLabel10.setText("Chocolate");

        jLabel11.setText("Cocaina");

        txtCocaina.setEditable(false);
        txtCocaina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCocainaActionPerformed(evt);
            }
        });

        txtCrack.setEditable(false);
        txtCrack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCrackActionPerformed(evt);
            }
        });

        jLabel12.setText("Crack");

        txtEcstasy.setEditable(false);
        txtEcstasy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEcstasyActionPerformed(evt);
            }
        });

        jLabel13.setText("Ecstasy");

        jLabel14.setText("Heroina");

        txtHeroina.setEditable(false);
        txtHeroina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHeroinaActionPerformed(evt);
            }
        });

        txtKetamina.setEditable(false);
        txtKetamina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKetaminaActionPerformed(evt);
            }
        });

        jLabel15.setText("ketamina");

        jLabel16.setText("Drogas Legais");

        txtDrogas.setEditable(false);
        txtDrogas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDrogasActionPerformed(evt);
            }
        });

        txtLsd.setEditable(false);
        txtLsd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLsdActionPerformed(evt);
            }
        });

        jLabel17.setText("LSD");

        txtMetadona.setEditable(false);
        txtMetadona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMetadonaActionPerformed(evt);
            }
        });

        jLabel18.setText("Metadona");

        txtCogumelos.setEditable(false);
        txtCogumelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCogumelosActionPerformed(evt);
            }
        });

        jLabel19.setText("Cogumelos Magicos");

        txtNicotina.setEditable(false);
        txtNicotina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNicotinaActionPerformed(evt);
            }
        });

        jLabel20.setText("Nicotina");

        jLabel21.setText("VSA");

        txtVsa.setEditable(false);
        txtVsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVsaActionPerformed(evt);
            }
        });

        btnClassificar.setText("Classificar");
        btnClassificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClassificarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnComparar.setText("Classificar Parte da Base");
        btnComparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompararActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(390, 390, 390)
                .addComponent(titulo))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Sexo)
                .addGap(26, 26, 26)
                .addComponent(jComboSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Idade)
                .addGap(4, 4, 4)
                .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(jComboEtnia, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170)
                .addComponent(jLabel3))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)
                        .addGap(17, 17, 17)
                        .addComponent(jComboEducacao, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnClassificar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180)
                        .addComponent(btnComparar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel4)
                        .addGap(62, 62, 62)
                        .addComponent(jLabel5)
                        .addGap(70, 70, 70)
                        .addComponent(jLabel6)
                        .addGap(51, 51, 51)
                        .addComponent(jLabel7)
                        .addGap(56, 56, 56)
                        .addComponent(jLabel8)
                        .addGap(73, 73, 73)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtAlcool, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtAnfetaminas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtMaconha, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtNitrito, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtBenzodiazepina, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtCafeina, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel10)
                        .addGap(72, 72, 72)
                        .addComponent(jLabel11)
                        .addGap(82, 82, 82)
                        .addComponent(jLabel12)
                        .addGap(63, 63, 63)
                        .addComponent(jLabel15)
                        .addGap(57, 57, 57)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel17))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtChocolate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtCocaina, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtCrack, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtKetamina, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtDrogas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtVsa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel13)
                        .addGap(73, 73, 73)
                        .addComponent(jLabel14)
                        .addGap(73, 73, 73)
                        .addComponent(jLabel18)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel19)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel20)
                        .addGap(82, 82, 82)
                        .addComponent(jLabel21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtEcstasy, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtHeroina, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtLsd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtCogumelos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtNicotina, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtMetadona, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(titulo)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(Sexo))
                    .addComponent(jComboSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(Idade))
                    .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addComponent(jComboEtnia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel3)))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jComboEducacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnClassificar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnComparar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAlcool, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAnfetaminas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaconha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNitrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBenzodiazepina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCafeina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtChocolate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCocaina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCrack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKetamina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDrogas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVsa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEcstasy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHeroina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLsd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCogumelos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNicotina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMetadona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtVsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVsaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVsaActionPerformed

    private void txtNicotinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNicotinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNicotinaActionPerformed

    private void txtCogumelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCogumelosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCogumelosActionPerformed

    private void txtMetadonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMetadonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMetadonaActionPerformed

    private void txtLsdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLsdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLsdActionPerformed

    private void txtDrogasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDrogasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDrogasActionPerformed

    private void txtKetaminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKetaminaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKetaminaActionPerformed

    private void txtHeroinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHeroinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHeroinaActionPerformed

    private void txtEcstasyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEcstasyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEcstasyActionPerformed

    private void txtCrackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCrackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCrackActionPerformed

    private void txtCocainaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCocainaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCocainaActionPerformed

    private void txtChocolateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChocolateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChocolateActionPerformed

    private void txtMaconhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaconhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaconhaActionPerformed

    private void txtCafeinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCafeinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCafeinaActionPerformed

    private void txtBenzodiazepinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBenzodiazepinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBenzodiazepinaActionPerformed

    private void txtNitritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNitritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNitritoActionPerformed

    private void txtAnfetaminasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnfetaminasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnfetaminasActionPerformed

    private void txtAlcoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlcoolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlcoolActionPerformed

    private void txtIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdadeActionPerformed

    private void jComboSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboSexoActionPerformed

    private void btnClassificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClassificarActionPerformed

        converteSexo((String) jComboSexo.getSelectedItem());
        converteIdade(Integer.parseInt(txtIdade.getText()));
        converteEducacao((String) jComboEducacao.getSelectedItem());
        converteEtnia((String) jComboEtnia.getSelectedItem());
        if (IDADE == -1) {
            JOptionPane.showMessageDialog(null, "Idade Inválida !");
        } else {
            Padrao p = new Padrao(IDADE, G1, G2, GRAU, ET1, ET2, ET3, ET4, ET5, ET6, ET7, null, 0);
            k = new Classificador();
            result = k.Classificar(p);
            String[] r = result.split(":");

            txtAlcool.setText(classifica(r[0]));
            txtAnfetaminas.setText(classifica(r[1]));
            txtNitrito.setText(classifica(r[2]));
            txtBenzodiazepina.setText(classifica(r[3]));
            txtCafeina.setText(classifica(r[4]));
            txtMaconha.setText(classifica(r[5]));
            txtChocolate.setText(classifica(r[6]));
            txtCocaina.setText(classifica(r[7]));
            txtCrack.setText(classifica(r[9]));
            txtEcstasy.setText(classifica(r[10]));
            txtHeroina.setText(classifica(r[11]));
            txtKetamina.setText(classifica(r[12]));
            txtDrogas.setText(classifica(r[13]));
            txtLsd.setText(classifica(r[14]));
            txtMetadona.setText(classifica(r[15]));
            txtCogumelos.setText(classifica(r[16]));
            txtNicotina.setText(classifica(r[18]));
            txtVsa.setText(classifica(r[19]));

            jTextLog.setText(Log.resumo());

        }


    }//GEN-LAST:event_btnClassificarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        Log.LOG.clear();
        txtAlcool.setText("");
        txtAnfetaminas.setText("");
        txtNitrito.setText("");
        txtBenzodiazepina.setText("");
        txtCafeina.setText("");
        txtMaconha.setText("");
        txtChocolate.setText("");
        txtCocaina.setText("");
        txtCrack.setText("");
        txtEcstasy.setText("");
        txtHeroina.setText("");
        txtKetamina.setText("");
        txtDrogas.setText("");
        txtLsd.setText("");
        txtMetadona.setText("");
        txtCogumelos.setText("");
        txtNicotina.setText("");
        txtVsa.setText("");
        jTextLog.setText("");


    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnCompararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompararActionPerformed
        float[] porc = k.ClassificarParcial();
        txtAlcool.setText("" + porc[0] + "%");
        txtAnfetaminas.setText("" + porc[1] + "%");
        txtNitrito.setText("" + porc[2] + "%");
        txtBenzodiazepina.setText("" + porc[3] + "%");
        txtCafeina.setText("" + porc[4] + "%");
        txtMaconha.setText("" + porc[5] + "%");
        txtChocolate.setText("" + porc[6] + "%");
        txtCocaina.setText("" + porc[7] + "%");
        txtCrack.setText("" + porc[9] + "%");
        txtEcstasy.setText("" + porc[10] + "%");
        txtHeroina.setText("" + porc[11] + "%");
        txtKetamina.setText("" + porc[12] + "%");
        txtDrogas.setText("" + porc[13] + "%");
        txtLsd.setText("" + porc[14] + "%");
        txtMetadona.setText("" + porc[15] + "%");
        txtCogumelos.setText("" + porc[16] + "%");
        txtNicotina.setText("" + porc[18] + "%");
        txtVsa.setText("" + porc[19] + "%");

        jTextLog.setText("");
        jTextLog.setText("" + LogClassParcial.resumo());
    }//GEN-LAST:event_btnCompararActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Idade;
    private javax.swing.JLabel Sexo;
    private javax.swing.JButton btnClassificar;
    private javax.swing.JButton btnComparar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JComboBox<String> jComboEducacao;
    private javax.swing.JComboBox<String> jComboEtnia;
    private javax.swing.JComboBox<String> jComboSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextArea jTextLog;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtAlcool;
    private javax.swing.JTextField txtAnfetaminas;
    private javax.swing.JTextField txtBenzodiazepina;
    private javax.swing.JTextField txtCafeina;
    private javax.swing.JTextField txtChocolate;
    private javax.swing.JTextField txtCocaina;
    private javax.swing.JTextField txtCogumelos;
    private javax.swing.JTextField txtCrack;
    private javax.swing.JTextField txtDrogas;
    private javax.swing.JTextField txtEcstasy;
    private javax.swing.JTextField txtHeroina;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtKetamina;
    private javax.swing.JTextField txtLsd;
    private javax.swing.JTextField txtMaconha;
    private javax.swing.JTextField txtMetadona;
    private javax.swing.JTextField txtNicotina;
    private javax.swing.JTextField txtNitrito;
    private javax.swing.JTextField txtVsa;
    // End of variables declaration//GEN-END:variables

    public void converteSexo(String sexo) {
        if (sexo.equals("Masculino")) {
            G1 = 0;
            G2 = 1;
        } else {
            G1 = 1;
            G2 = 0;
        }
    }

    public void converteIdade(int idade) {

        if (idade >= 18 && idade <= 24) {
            IDADE = 0;
        } else if (idade > 24 && idade <= 34) {
            IDADE = 0.246;
        } else if (idade > 34 && idade <= 44) {
            IDADE = 0.409;
        } else if (idade > 44 && idade <= 54) {
            IDADE = 0.577;
        } else if (idade > 54 && idade <= 64) {
            IDADE = 0.783;
        } else if (idade > 64) {
            IDADE = 1;
        } else {
            IDADE = -1;
        }

    }

    public void converteEducacao(String educa) {
        switch (educa) {
            case "Desistiu da escola antes dos 16 Anos":
                GRAU = 0;
                break;
            case "Desistiu da escola aos 16 anos":
                GRAU = 0.158;
                break;
            case "Desistiu da escola aos 17 anos":
                GRAU = 0.226;
                break;
            case "Desistiu da escola aos 18 anos":
                GRAU = 0.273;
                break;
            case "Alguma facul/uni sem certificado ou grau":
                GRAU = 0.413;
                break;
            case "Certificado / diploma profissional":
                GRAU = 0.538;
                break;
            case "Diploma Universitário":
                GRAU = 0.654;
                break;
            case "Mestrado":
                GRAU = 0.814;
                break;
            case "Doutorado":
                GRAU = 1;
                break;
        }
    }

    public void converteEtnia(String etnia) {
        switch (etnia) {
            case "Asiático":
                ET1 = 0;
                ET2 = 0;
                ET3 = 0;
                ET4 = 0;
                ET5 = 0;
                ET6 = 0;
                ET7 = 1;
                break;
            case "Negro":
                ET1 = 0;
                ET2 = 0;
                ET3 = 0;
                ET4 = 0;
                ET5 = 0;
                ET6 = 1;
                ET7 = 0;
                break;
            case "Branco":
                ET1 = 1;
                ET2 = 0;
                ET3 = 0;
                ET4 = 0;
                ET5 = 0;
                ET6 = 0;
                ET7 = 0;
                break;
            case "Misto Negro/Asiatico":
                ET1 = 0;
                ET2 = 0;
                ET3 = 0;
                ET4 = 0;
                ET5 = 1;
                ET6 = 0;
                ET7 = 0;
                break;
            case "Misto Branco/Asiatico":
                ET1 = 0;
                ET2 = 0;
                ET3 = 0;
                ET4 = 1;
                ET5 = 0;
                ET6 = 0;
                ET7 = 0;
                break;
            case "Misto Branco/Negro":
                ET1 = 0;
                ET2 = 0;
                ET3 = 1;
                ET4 = 0;
                ET5 = 0;
                ET6 = 0;
                ET7 = 0;
                break;
            case "Outro":
                ET1 = 0;
                ET2 = 1;
                ET3 = 0;
                ET4 = 0;
                ET5 = 0;
                ET6 = 0;
                ET7 = 0;
                break;
        }

    }

    public String classifica(String r) {
        switch (r) {
            case "CL0":
                return "Baixo";
            case "CL1":
                return "Baixo";
            case "CL2":
                return "Medio";
            case "CL3":
                return "Medio";
            case "CL4":
                return "Alto";
            case "CL5":
                return "Alto";
            case "CL6":
                return "Alto";
            default:
                return "Error";
        }
    }
}
